## day01
###      00_flink实时数仓_项目需求介绍.mp4
###      01_flink实时数仓_离线和实时架构介绍.mp4
###      02_flink实时数仓_日志数据采集环境搭建.mp4
###      03_flink实时数仓_SSM介绍.mp4
###      04_flink实时数仓_基本SpringMVC功能实现.mp4
###      05_flink实时数仓_SpringMVC参数处理.mp4
###      06_flink实时数仓_上午内容回顾.mp4
###      07_flink实时数仓_接收日志数据打印到控制台.mp4
###      08_flink实时数仓_通过logback实现打印和落盘.mp4
###      09_flink实时数仓_Kafka命令回顾.mp4
###      10_flink实时数仓_Kafka原生API发送消息.mp4
###      11_flink实时数仓_使用KafkaTemplate向kafka主题发送消息.mp4
###      12_flink实时数仓_打包到服务器(单机).mp4
###      13_flink实时数仓_集群思路分析.mp4
###      14_flink实时数仓_Nginx安装.mp4
###      15_flink实时数仓_Nginx负载均衡配置.mp4
###      16_flink实时数仓_打包到服务器(集群).mp4
###
## day02
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_封装日志采集服务群起脚本.mp4
###      02_flink实时数仓_binlog介绍.mp4
###      03_flink实时数仓_binlog配置.mp4
###      04_flink实时数仓_业务数据的准备以及生成.mp4
###      05_flink实时数仓_maxwell配置以及业务数据采集.mp4
###      06_flink实时数仓_DWD层需求分析.mp4
###      07_flink实时数仓_实时开发环境搭建.mp4
###      08_flink实时数仓_日志数据分流思路分析.mp4
###      09_flink实时数仓_上午内容回顾.mp4
###      10_flink实时数仓_日志数据分流代码思路.mp4
###      11_flink实时数仓_基本环境准备以及检查点设置.mp4
###      12_flink实时数仓_从Kafka中读取数据以及封装kafka工具类中的获取Consumer对象的方法.mp4
###      13_flink实时数仓_对流中数据进行类型转换以及测试.mp4
###      14_flink实时数仓_新老访客标记修复思路以及分组实现.mp4
###      15_flink实时数仓_状态的声明以及初始化.mp4
###      16_flink实时数仓_新老访客标记修复代码实现.mp4
###      17_flink实时数仓_日志数据分流.mp4
###
## day03
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_将不同流数据写到kafka主题.mp4
###      02_flink实时数仓_动态分流思路1.mp4
###      03_flink实时数仓_动态分流思路2.mp4
###      04_flink实时数仓_FlinkCDC介绍.mp4
###      05_flink实时数仓_上午内容回顾.mp4
###      06_flink实时数仓_CDC介绍以及配置库准备.mp4
###      07_flink实时数仓_FlinkCDC读取MySQL数据_API方式.mp4
###      08_flink实时数仓_检查点记录FinkCDC读取数据的偏移量.mp4
###      09_flink实时数仓_FlinkCDC读取MySQL数据_SQL方式.mp4
###      10_flink实时数仓_自定义反序列化器.mp4
###      11_flink实时数仓_业务数据分流代码思路.mp4
###      12.mp4
###
## day04
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_barrier对齐理解.mp4
###      02_flink实时数仓_配置表以及对应的实体类创建.mp4
###      03_flink实时数仓_使用FlinkCDC读取配置信息.mp4
###      04_flink实时数仓_抽取TableProcessFunction类完成动态分流.mp4
###      05_flink实时数仓_处理广播流数据.mp4
###      06_flink实时数仓_通过Debug熟悉广播流处理流程.mp4
###      07_flink实时数仓_处理主流数据.mp4
###      08_flink实时数仓_动态分流基本思路总结.mp4
###      09_flink实时数仓_上午内容回顾.mp4
###      10_flink实时数仓_提前创建维度表思路分析.mp4
###      11_flink实时数仓_拼接建表语句.mp4
###      12_flink实时数仓_执行建表语句.mp4
###      13_flink实时数仓_建表常见问题说明.mp4
###      14_flink实时数仓_字段过滤.mp4
###
## day05
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_维度侧输出流数据写入思路分析.mp4
###      02_flink实时数仓_拼接upsert语句.mp4
###      03_flink实时数仓_使用JDBC执行upsert语句.mp4
###      04_flink实时数仓_执行测试以及常见问题解决.mp4
###      05_flink实时数仓_重写获取FlinkKafkaProducer方法.mp4
###      06_flink实时数仓_重写获取支持精准一次的FlinkKafkaProducer的方法.mp4
###      07_flink实时数仓_业务数据整体分流测试.mp4
###      08_flink实时数仓_业务数据动态分流思路总结.mp4
###      09_flink实时数仓_DWM业务介绍.mp4
###      10_flink实时数仓_UV独立访客思路分析.mp4
###      11_flink实时数仓_从kafka中读取数据.mp4
###      12_flink实时数仓_状态失效时间设置.mp4
###      13_flink实时数仓_独立访客过滤实现.mp4
###      14_flink实时数仓_独立访客整体测试以及流程总结.mp4
###
## day06
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_跳出行为分析.mp4
###      02_flink实时数仓_用户跳出实现思路分析.mp4
###      03_flink实时数仓_从kafka中读取数据.mp4
###      04_flink实时数仓_Watermark指定以及事件时间字段提取.mp4
###      05_flink实时数仓_pattern定义思路分析.mp4
###      06_flink实时数仓_pattern的定义以及应用到流上.mp4
###      07_flink实时数仓_从流中提取数据方式介绍.mp4
###      08_flink实时数仓_从流中提取超时数据.mp4
###      09_flink实时数仓_用户跳出明细测试.mp4
###      10_flink实时数仓_订单宽表实现思路分析.mp4
###      11_flink实时数仓_订单宽表代码实现思路分析.mp4
###      12_flink实时数仓_从kafka中读取订单和订单明细主题数据.mp4
###      13_flink实时数仓_定义订单和明细实体类.mp4
###      14_flink实时数仓_对流中的数据类型进行转换.mp4
###      15_flink实时数仓_Watermark的指定以事件时间字段提取.mp4
###      16_flink实时数仓_intervalJoin介绍.mp4
###      17_flink实时数仓_双流join的实现.mp4
###      18_flink实时数仓_订单和明细关联测试.mp4
###      19_flink实时数仓_intervalJoin底层实现分析.mp4
###
## day07
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_封装PhoenixUtil工具类以及实现思路.mp4
###      02_flink实时数仓_连接对象的创建.mp4
###      03_flink实时数仓_对结果集的处理1.mp4
###      04_flink实时数仓_对结果集的处理2.mp4
###      05_flink实时数仓_查询维度的工具类的封装.mp4
###      06_flink实时数仓_维度查询工具类整体实现.mp4
###      07_flink实时数仓_旁路缓存介绍.mp4
###      08_flink实时数仓_redis启动注意事项.mp4
###      09_flink实时数仓_封装操作Redis的工具类.mp4
###      10_flink实时数仓_上午内容回顾.mp4
###      11_flink实时数仓_旁路缓存实现思路分析.mp4
###      12_flink实时数仓_旁路缓存代码实现.mp4
###      13_flink实时数仓_维度数据修改删除缓存.mp4
###      14_flink实时数仓_基本维度关联实现.mp4
###      15_flink实时数仓_异步IO分析.mp4
###      16_flink实时数仓_发送异步请求思路.mp4
###      17_flink实时数仓_双重校验锁解决单例设计模式懒汉式线程安全问题.mp4
###      18_flink实时数仓_总结.mp4
###      Redis面试题-先更新数据库还是先更新缓存.docx
###      实时数仓.bmpr
###
## day08
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_维度存储数据库选择疑问解答.mp4
###      02_flink实时数仓_抽取发送异步请求的类DimAsyncFunction.mp4
###      03_flink实时数仓_模板方法设计进行异步维度关联思路.mp4
###      04_flink实时数仓_用户维度关联实现.mp4
###      05_flink实时数仓_和用户维度关联测试.mp4
###      06_flink实时数仓_和地区维度关联.mp4
###      07_flink实时数仓_和商品维度关联.mp4
###      08_flink实时数仓_和其他维度进行关联以及写到kafka主题.mp4
###      09_flink实时数仓_订单宽表实现总结.mp4
###      10_flink实时数仓_模板方法设计模式应用场景.mp4
###      11_flink实时数仓_从kafka中读取数据.mp4
###      12_flink实时数仓_从Kafka中读取数据测试.mp4
###      13_flink实时数仓_对流中的数据类型进行转换.mp4
###      14_flink实时数仓_指定Watermark以及封装日期工具类.mp4
###      15_flink实时数仓_支付和订单宽表双流join以及整体测试.mp4
###
## day09
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_DWS层说明.mp4
###      02_flink实时数仓_访客主题统计思路分析.mp4
###      03_flink实时数仓_从kafka主题中读取数据.mp4
###      04_flink实时数仓_将pageLog流数据类型进行转换.mp4
###      05_flink实时数仓_合并各个流的数据并测试.mp4
###      06_flink实时数仓_按照维度进行分组.mp4
###      07_flink实时数仓_开窗.mp4
###      08_flink实时数仓_聚合操作.mp4
###      09_flink实时数仓_聚合操作测试.mp4
###      10_flink实时数仓_ClickHouse介绍.mp4
###      11_flink实时数仓_上午内容回顾.mp4
###      12_flink实时数仓_安装准备工作.mp4
###      13_flink实时数仓_单机安装.mp4
###      14_flink实时数仓_整数数据类型.mp4
###      15_flink实时数仓_其它数据类型.mp4
###      16_flink实时数仓_partitionby.mp4
###      17_flink实时数仓_primaryKey和orderBy.mp4
###      18_flink实时数仓_二级索引以及TTL(了解).mp4
###      19_flink实时数仓_ReplacingMergeTree.mp4
###      20_flink实时数仓_SummingMergeTree.mp4
###
## day10
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_SQL操作.mp4
###      02_flink实时数仓_副本写入流程.mp4
###      03_flink实时数仓_副本zk服务器的配置.mp4
###      04_flink实时数仓_副本测试.mp4
###      05_flink实时数仓_分片集群读写流程.mp4
###      06_flink实时数仓_分片集群配置.mp4
###      07_flink实时数仓_分片集群测试.mp4
###      08_flink实时数仓_抽取操作ClickHouse的工具类.mp4
###      09_flink实时数仓_给问号占位符赋值.mp4
###      10_flink实时数仓_自定义注解标记不需要保存到CK的属性.mp4
###      11_flink实时数仓_构造者设计模式.mp4
###      12_flink实时数仓_商品统计思路分析.mp4
###      13_flink实时数仓_从Kafka中读取商品主题相关数据.mp4
###      14_flink实时数仓_封装商品统计实体类.mp4
###      15_flink实时数仓_商品点击行为的处理.mp4
###      16_flink实时数仓_商品曝光行为的处理.mp4
###      17_flink实时数仓_商品收藏行为的处理.mp4
###
## day11
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_商品加购行为的处理.mp4
###      02_flink实时数仓_商品下单行为的处理.mp4
###      03_flink实时数仓_商品支付、退单、评论行为的处理.mp4
###      04_flink实时数仓_对合并结果进行测试.mp4
###      05_flink实时数仓_分组、开窗、聚合操作.mp4
###      06_flink实时数仓_支付回调时间提前生成现象解释.mp4
###      07_flink实时数仓_和商品维度进行关联.mp4
###      08_flink实时数仓_商品统计整体测试.mp4
###      09_flink实时数仓_地区主题统计需求分析.mp4
###      10_flink实时数仓_从Kafka主题中读取数据创建动态表.mp4
###      11_flink实时数仓_指定Watermark以及提取事件时间字段.mp4
###      12_flink实时数仓_分组、聚合.mp4
###      13_flink实时数仓_开窗操作.mp4
###      14_flink实时数仓_地区主题统计测试.mp4
###      15_flink实时数仓_关键词统计需求说明.mp4
###      16_flink实时数仓_封装IK分词工具类.mp4
###      17_flink实时数仓_自定义UDTF函数.mp4
###      18_flink实时数仓_从kafka中读取数据创建动态表.mp4
###      19_flink实时数仓_过滤数据以及分词并和原表字段连接.mp4
###      20_flink实时数仓_关键词统计测试.mp4
###
## day12
###      00_flink实时数仓_内容回顾.mp4
###      01_flink实时数仓_大屏展示需求介绍.mp4
###      02_flink实时数仓_Sugar可视化组件介绍.mp4
###      03_flink实时数仓_商品总交易额思路分析.mp4
###      04_flink实时数仓_项目整体架构搭建.mp4
###      05_flink实时数仓_总交易额mapper接口定义.mp4
###      06_flink实时数仓_总交易额service代码实现.mp4
###      07_flink实时数仓_总交易额controller代码实现.mp4
###      08_flink实时数仓_总交易额大屏展示以及内网穿透.mp4
###      09_flink实时数仓_品牌交易额排名思路分析.mp4
###      10_flink实时数仓_品牌交易额排名Mapper层实现.mp4
###      11_flink实时数仓_上午内容回顾.mp4
###      12_flink实时数仓_品牌交易额controller实现以及大屏展示.mp4
###      13_flink实时数仓_品牌交易额占比整体实现.mp4
###      14_flink实时数仓_宏变量定义以及面向对象的方式处理返回的json.mp4
###      15_flink实时数仓_SPU交易额思路分析.mp4
###      16_flink实时数仓_SPU交易额代码实现.mp4
###      17_flink实时数仓_地区交易额思路分析.mp4
###      18_flink实时数仓_地区交易额代码实现以及大屏展示.mp4
###      实时数仓.bmpr
###      数据接口服务开发思路分析.txt
###
## day13
###       00_flink实时数仓_新老访客指标对比思路分析.mp4
###       01_flink实时数仓_新老访客指标对比代码实现.mp4
###       02_flink实时数仓_访客指标分时统计思路分析.mp4
###       03_flink实时数仓_访客指标分时统计代码实现.mp4
###       04_flink实时数仓_关键词统计整体实现.mp4
###       05_flink实时数仓_关键词统计实时展示流程分析.mp4
###       06_flink实时数仓_关键词统计实时展示演示.mp4
###       07_flink实时数仓_打包到服务器运行流程.mp4
###       08_flink实时数仓_实时数仓项目回顾.mp4
###       09_Fink以及面试总结_基本理论.mp4
###       10_Fink以及面试总结_Watermark.mp4
###       11_Fink以及面试总结_keyby原理.mp4
###       12_Fink以及面试总结_资源分配.mp4
###       13_Fink以及面试总结_窗口.mp4
###       14_Fink以及面试总结_一致性以及反压.mp4
###       实时数仓.bmpr
###       数据接口服务开发思路分析.txt
###       面试.mkv
